apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jobsback:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /backend/sofijobs.db
            name: database-volume
            subPath: sofijobs.db
            readOnly: false
      volumes:
        - name: database-volume
          hostPath:
            path: backend/sofijobs.db
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000